### ISSUE TITLE
Changes to APC pricing box

### ISSUE THREAD

**Issue by aliallover** [PeerJ/peerj.github.io#12]
![image](https://user-images.githubusercontent.com/7261527/72890688-6152b900-3d0a-11ea-9486-775df3ffb294.png)

- Change price to correct current pricing
- Copy change
> PeerJ offers low-cost article-processing charges and discounts for active reviewers. Plus, it is currently free to publish in our PeerJ Chemistry journals.

**Comment by markpeerj** [comment]
@aliallover What is the correct current pricing?
Should that quoted bit of text replace the top paragraph?

**Comment by aliallover** [comment]
- _start at $995_
- Replace: '_Publishing can cost... .. for figures_" text with 
> PeerJ offers low-cost article-processing charges and discounts for active reviewers. Plus, it is currently free to publish in our PeerJ Chemistry journals.
